[project]
authors = ["Daniel Cain <daniel.cain@pnnl.gov>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "comms-freq-sync-py"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
rust = "*"
maturin = "*"
